[{"id":604329826,"node_id":"R_kgDOJAVXYg","name":"CVE-2021-4034_Python3","full_name":"c0d3cr4f73r/CVE-2021-4034_Python3","private":false,"owner":{"login":"c0d3cr4f73r","id":66146701,"node_id":"MDQ6VXNlcjY2MTQ2NzAx","avatar_url":"https://avatars.githubusercontent.com/u/66146701?v=4","url":"https://api.github.com/users/c0d3cr4f73r","html_url":"https://github.com/c0d3cr4f73r","type":"User","site_admin":false},"html_url":"https://github.com/c0d3cr4f73r/CVE-2021-4034_Python3","description":"","fork":false,"url":"https://api.github.com/repos/c0d3cr4f73r/CVE-2021-4034_Python3","created_at":"2023-02-20T20:39:32Z","updated_at":"2023-02-20T20:40:22Z","pushed_at":"2023-02-20T20:40:31Z","stargazers_count":0,"watchers_count":0,"forks_count":0,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":[],"visibility":"public","forks":0,"watchers":0,"default_branch":"main","score":1}]